### ISSUE TITLE
Display donations in the same table as Smooth blocks and add filtering option

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/mev-sp-fe#30]
Donations should be added to the list of incoming ETH into the pool.

This way, all fields in this add to the total rewards that will be distributed, including fees.

To be correct with the name of the columns, change proposer to "sender":
<img width="1322" alt="Screenshot 2023-11-17 at 11 23 48" src="https://github.com/dappnode/mev-sp-fe/assets/19168735/63c8db23-b06f-44d3-9395-f8fa8006edd9">

**Comment by Marketen** [comment]
We will have to rename the table to Latest Smooth Blocks & Donations too.
