### ISSUE TITLE
Improve validators monthly rewards card

### ISSUE THREAD

**Issue by Marketen** [dappnode/mev-sp-fe#59]
![image](https://github.com/dappnode/mev-sp-fe/assets/36164126/75e246c5-7234-45a9-9ea0-0487c4abaacf)

This ETH amount can be deterrent. We should find another stat

**Comment by Pol-Lanski** [comment]
Done: 
<img width="327" alt="Screenshot 2023-12-19 at 17 26 10" src="https://github.com/dappnode/mev-sp-fe/assets/19168735/eea52d64-c447-4b54-8b1c-c4f86049e200">
