### ISSUE TITLE
Change How to Use to a link to the manual subscription and change How to Use page's title to Why Smooth

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/mev-sp-fe#72]
Change How to Use to a link to the manual subscription and change How to Use page's title to Why Smooth

**Comment by Pol-Lanski** [comment]
<img width="779" alt="Screenshot 2023-12-19 at 17 34 26" src="https://github.com/dappnode/mev-sp-fe/assets/19168735/663fc7cb-b1a0-4d24-a9c1-feb1fdc04060">

**Comment by GiselleNessi** [comment]
PR is open for this fix

**Comment by GiselleNessi** [comment]
This has been merged to dev
