### ISSUE TITLE
Add a "Date" column between "Slot" and "Proposer" in the Latest Smooth Blocks table

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/mev-sp-fe#73]
The Date should be in Local Time if possible, otherwise in UTC.

I don't know if we can get the time and date directly, otherwise: Slots are 12 secs, and we should be able to count since Genesis by knowing what Genesis time is in Unix time (https://www.utctime.net/utc-timestamp) and adding genesis time to (slotnumber * 12).

**Comment by Marketen** [comment]
Oracle doesnt provide time and date directly, but we can get it as you point out with unix time & genesis timestamp

**Comment by Pol-Lanski** [comment]
Greatly executed
